### ISSUE TITLE
Поправки в граматиката

### ISSUE THREAD

**Issue by Gismo359** [ymarinov1998/ep_homework#1]
В момента, граматиката е двусмислена и не съвпада с приоритетите на аритметичните операции.
Препоръчително е да се образува от приоритета на различните изрази, поддържани от езика.

Ще се получат правила от този вид:
``<Expression> ::= <TernaryOperator>``
``<TernaryOperator> ::= <BooleanOr> ( IF <BooleanOr> ELSE <BooleanOr> ) ?``
``<BooleanOr> ::= <BooleanAnd> ( OR <BooleanOr> ) ?``

По този начин граматиката ясно описва йерархията на операциите и не се налагат допълнителни частни случаи при анализа.

**Comment by yomarinov** [comment]
След малки редакции стигнах до следното решение:
```
expression -> conditional_expression ( IF conditional_expression ELSE conditional_expression )?
conditional_expression -> simple_expression | simple_expression relational_operator simple_expression
simple_expression -> signed_term ( ( additive_operator | OR ) simple_expression )?
signed_term -> (unary_operator)? term
term -> factor ( ( multiplicative_operator | AND ) signed_term )?
factor -> variable | INT_LITERAL | BOOLEAN_LITERAL | LPAREN expression RPAREN | function_call
```
Има ли нужда AND и OR да бъдат отделени в свои собствени правила или могат да останат при multiplicative_operator и additive_operator, респективно? Ако има нужда да бъдат отделени, каква е последователността от приоритети, които трябва да следвам? (Пример: ternary op -> AND и OR -> събиране и изваждане -> умножение и деление -> NOT и MINUS или някаква друга последователност?)

**Comment by Gismo359** [comment]
Може да следваш приоритетите от тук: https://en.cppreference.com/w/cpp/language/operator_precedence
Получава се нещо като ``Ternary -> Or -> And -> ==/!= -> >/>=/</<= -> Add/Sub -> Mul/Div -> Unary -/+/not``
В C++ присвояването е израз, който връща резултат, но в случая е по-добре да е отделна операция (тоест Statement, а не Expression)
За всеки приоритет е нужен отделен нетерминал.
